name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Check VPS_HOST Secret
      run: |
        if [ -z "${{ secrets.VPS_HOST }}" ]; then
          echo "Error: VPS_HOST secret is not set or empty"
          exit 1
        else
          echo "VPS_HOST is properly configured: ${{ secrets.VPS_HOST }}"
        fi
        
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script_stop: true
        script: |
          cd /var/www/library-management
          git pull origin main
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          docker system prune -f

    # - name: Backup Database
    #   if: github.ref == 'refs/heads/main'
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.VPS_HOST }}
    #     username: ${{ secrets.VPS_USERNAME }}
    #     key: ${{ secrets.VPS_SSH_KEY }}
    #     script: |
    #       cd /path/to/project
    #       TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    #       docker exec library-management-system-mongodb mongodump --out /backup/$TIMESTAMP
    #       tar -czf /backup/mongodb_$TIMESTAMP.tar.gz /backup/$TIMESTAMP
    #       rm -rf /backup/$TIMESTAMP
    #       # Giữ lại 7 backup gần nhất
    #       ls -t /backup/mongodb_*.tar.gz | tail -n +8 | xargs -r rm